export const ADD_RECENT = 'ADD_RECENT'
export const DELETE_RECENT = 'DELETE_RECENT'

export const SET_SERIAL_INPUT_TEXT = 'SET_SERIAL_INPUT_TEXT'

export const ADD_PRESET = 'ADD_PRESET'
export const DELETE_PRESET = 'DELETE_PRESET'
export const EDIT_PRESET = 'EDIT_PRESET'
export const SET_PRESET = 'FETCH_PRESET'
